---
- name: Icx command module
  hosts: devruckus
  tasks:
   - name: Get local system date
     ansible.builtin.command: date +"%b %d"
     register: systemdate
     changed_when: systemdate.rc != 0
   - name: Get System Logging
     community.network.icx_command:
      commands: show logging | include {{ systemdate.stdout | trim }}
     register: log
   - name: Create root Directory
     ansible.builtin.file:
      path: /log/{{ inventory_hostname }}
      state: directory
      mode: "0755"
   - name: Create log Directory
     ansible.builtin.file:
      path: /log/{{ inventory_hostname }}/log
      state: directory
      mode: "0755"
   - name: Save Last Log
     ansible.builtin.copy:
      content: "{{ log.stdout | replace('\\n', '\n') }}"
      dest: "/log/{{ inventory_hostname }}/log/{{ inventory_hostname }}{{ lookup('pipe', 'date +%m%d%Y-%H%M') }}.log"
      mode: "0644"
