---
- name: Icx command module
  hosts: devruckus
  tasks:
   - name: Show version
     community.network.icx_command:
      commands: show version
     register: version
   - name: Create root Directory
     ansible.builtin.file:
      path: /log/{{ group_names[0] }}
      state: directory
      mode: "0755"
   - name: Create Device Directory
     ansible.builtin.file:
      path: /log/{{ group_names[0] }}/{{ inventory_hostname }}
      state: directory
      mode: "0755"
   - name: Create version Directory
     ansible.builtin.file:
      path: /log/{{ group_names[0] }}/{{ inventory_hostname }}/version
      state: directory
      mode: "0755"
   - name: Save output version
     ansible.builtin.copy:
      content: "{{ version.stdout | replace('\\n', '\n') }}"
      dest: "/log/{{ group_names[0] }}/{{ inventory_hostname }}/version/{{ inventory_hostname }}{{ lookup('pipe', 'date +%m%d%Y-%H%M') }}.ver"
      mode: "0644"
   - name: pull nginx image
   